[package]
name = "red_asn1"
version = "0.1.0"
authors = ["Zer1t0 <Zer1t0@mail.com>"]
edition = "2018"

[dependencies]
ascii = "0.9.1"
chrono = "0.4"
failure = "0.1.5"
failure_derive = "0.1.5"
red_asn1_derive = { path = "../red_asn1_derive" }
