---
name: Audit

# Trigger the workflow on push or pull request
"on":
  pull_request:
    branches:
      - master

env:
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.4
        with:
          version: "v0.4.2"
      - name: Install dependencies
        run: |
          cargo install cargo-audit

      - name: "Run audit"
        run: cargo audit
        continue-on-error: false
